### ISSUE TITLE
`/system send some-cmd` doesn't work if there are umlauts in some-cmd's output 

### ISSUE THREAD

**Issue by ikr** [boothj5/profanity-plugins#8]
Tried on macOS:

```
echo 'Äöü!' | pbcopy
```

Then in Profanity

```
/system send pbpaste
```

=> No output

Then, however, 

```
echo 'Aou!' | pbcopy
```

Then in Profanity

```
/system send pbpaste
```

Result:

```
11:04:06 - me:
           Aou!
```

**Comment by boothj5** [comment]
What happens if you just run the `echo` command without `pbcopy` and `pbpaste`?  For example I get:
```
/system send echo 'Äöü!'
...
22:05:23 - me: Äöü!
```
Which appears to be correct.

If you can provide the following information, I can take a look:
* The result of running the following in the console:
```
/plugins python_version
/charset
```

* The log at the time of running the command.

Thanks.

**Comment by ikr** [comment]
You know what, I've updated syscmd.py to the latest version, and executed `/system newline off`, and it all works fine now. Thank you! I'm closing the issue.
